### ISSUE TITLE
Catching Twilio Async Send SMS message Errors When host not available

### ISSUE THREAD

**Issue by mwaarna** [twilio/twilio-csharp#148]
Our work environment is behind a firewall and we create rules for the IP addresses for API.Twilio.com.

I am using the Async call to send SMS's, but when the IP address  changes or is unreachable , the async call throws an unhandled exception.

Question: How can I catch the unhandled exception without it crashing the application?

How to Reproduce issue.
1) Modify Host file to simulate IP Change(blocked access)
127.0.0.1 api.twilio.com
127.0.0.1 twilio.com
2) Send Async SMS
try
                {
var twilio = new TwilioRestClient(Twilio_AccountSid, Twilio_AuthToken);

```
                twilio.SendMessage(from, to, body, SMSProcessor.Properties.Settings.Default.Twilio_StatusCallBackURL, m =>
                {
                    MessageHandling.TwilioAsyncCallBack(m, sms); // Asynch Call Back
                });
```

}
                catch (Exception ex)
                {
                    Logger.ReportError("SendSMS", ex.ToString());
                }

Error Result:
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Twilio.Api
  StackTrace:
       at Twilio.TwilioRestClient.<>c__DisplayClass95`1.<ExecuteAsync>b__94(IRestResponse`1 response) in C:\Users\demo\Documents\GitHub\twilio-csharp\src\Twilio.Api.Silverlight\Core.Async.cs:line 41
       at RestSharp.RestClientExtensions.<>c__DisplayClass4`1.<ExecuteAsync>b__3(IRestResponse`1 response, RestRequestAsyncHandle asyncHandle)
       at RestSharp.RestClient.DeserializeResponse[T](IRestRequest request, Action`2 callback, IRestResponse response, RestRequestAsyncHandle asyncHandle)
       at RestSharp.RestClient.<>c__DisplayClassa`1.<ExecuteAsync>b__9(IRestResponse response, RestRequestAsyncHandle asyncHandle)
       at RestSharp.RestClient.ProcessResponse(IRestRequest request, HttpResponse httpResponse, RestRequestAsyncHandle asyncHandle, Action`2 callback)
       at RestSharp.RestClient.<>c__DisplayClass3.<ExecuteAsync>b__0(HttpResponse r)
       at RestSharp.Http.ExecuteCallback(HttpResponse response, Action`1 callback)
       at RestSharp.Http.RequestStreamCallback(IAsyncResult result, Action`1 callback)
       at RestSharp.Http.<>c__DisplayClassa.<WriteRequestBodyAsync>b__6(IAsyncResult result)
       at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Net.ContextAwareResult.Complete(IntPtr userToken)
       at System.Net.HttpWebRequest.SetResponse(Exception E)
       at System.Net.ConnectStream.ProcessWriteCallDone(ConnectionReturnResult returnResult)
       at System.Net.ConnectStream.CallDone(ConnectionReturnResult returnResult)
       at System.Net.ConnectStream.IOError(Exception exception, Boolean willThrow)
       at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
       at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
       at System.Net.TlsStream.ResumeIOWorker(Object result)
       at System.Net.TlsStream.WakeupPendingIO(IAsyncResult ar)
       at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
       at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslState.WriteCallback(IAsyncResult transportResult)
       at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Net.ContextAwareResult.Complete(IntPtr userToken)
       at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* nativeOverlapped)
       at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* pOVERLAP)
  InnerException:

**Comment by mwaarna** [comment]
Small Update..

Using AppDomain.UnhandledException Event:
http://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception.aspx

I am able to catch the Async error, log and report on it, but the application still crashes the service when the host is not available.

Any suggestions?

**Comment by devinrader** [comment]
Looking at the stack trace it looks like the error is happening in RestSharp.  I set up a simple console application to replicate the issue, but was unable to.  I'd suggest posting an issue over there.

**Comment by mwaarna** [comment]
I updated to the latest version of Twilio and Rest dll's and it no longer throws the error. I was receiving.

But on the Async Call back the twilio.message that is returned is NULL.

When Null is returned can I safely assume the message that was tried to be sent out never made it?

In what case's other than this one, would the twilio.message be returned back as NULL?

Thanks

**Comment by devinrader** [comment]
So to be clear, you are reayin that, in the code you posted earlier, now when you run it the m variable in the callback function is null, or its properties are null?

**Comment by mwaarna** [comment]
the m variable is returned as NULL.

**Comment by devinrader** [comment]
The only time I've seen that happen is when there is a transport layer failure (eg network failure, dns lookup failure).  In those cases I beleive RestSharp handles those exceptions and surfaces a couple of properties that tell you an error occured.  Unfortunately, today the Twilio library does not itself expose those properties so there is no way to check them.

**Comment by mwaarna** [comment]
that is exactly the scenario I am testing for.
I am setting the host mappings for Twilio to point to localhost to simulate a firewall change or network outage. 

But since the twilio library returns NULL in this case, can I assume that the sms sending failed completely?
I have a retry mechanism that will delay and retry again.

I just want to be sure that no user will get a duplicate message by accident.

**Comment by devinrader** [comment]
ya, I think thats a safe assumpion.  Next version of the library will hopefully surface this type of error in a more expected fashion (as an exception)

**Comment by jingming** [comment]
@mwaarna We just released an updated version of the library. Feel free to reopen the issue if you are still having trouble.
