### ISSUE TITLE
Cannot send multiple messages with single instance of TwilioRestClient

### ISSUE THREAD

**Issue by kamranayub** [twilio/twilio-csharp#185]
I cannot reuse the same instance of TwilioRestClient after sending one message. I confirmed this works only by changing Ninject to inject this class per instance instead of AsSingleton. Using beta async/await version 3.8.45-beta.

```
public class TwilioSender : ISmsSender
    {
        private readonly TwilioRestClient _twilio;

        public TwilioSender()
        {
            Require.Argument("TwilioAccountSid", AppSettings.TwilioAccountSid);
            Require.Argument("TwilioAuthToken", AppSettings.TwilioAuthToken);

            _twilio = new TwilioRestClient(AppSettings.TwilioAccountSid, AppSettings.TwilioAuthToken);
        }

        public async Task SendAsync(string to, string body)
        {
            if (string.IsNullOrWhiteSpace(to) || string.IsNullOrWhiteSpace(body))
                return;

            try
            {
                await _twilio.SendMessageAsync(AppSettings.TwilioFromNumber, to, body);
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error("Could not send SMS.", ex);
                throw;
            }
        }        
    }
```

I get this exception after sending one message and trying to send another:

```
System.InvalidOperationException: System.InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.
 at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
 at Twilio.TwilioRestClient.<SendMessageAsync>d__278.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
```

**Comment by devinrader** [comment]
Pretty sure this is a know issue in the prerelease version.  The current release version should not have this issue.

**Comment by kamranayub** [comment]
Thanks. I switched to prerelease because I need async. I'll just not use singleton until this is resolved fully then.
