### ISSUE TITLE
WorkspaceCreator fails to create a workspace

### ISSUE THREAD

**Issue by compgumby** [twilio/twilio-csharp#256]
_Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!_

**Version: Latest (bleeding?)**
**API Subdomain (api/taskrouter/v1):**
### Code Snippet

```
        var client = GetTwilioRestClient();
        var creator = new WorkspaceCreator(name);
        var result = creator.Execute(client);
```
# paste code here

```

### Exception / Log
```

"ClassName": "Newtonsoft.Json.JsonSerializationException",
  "Message": "ISerializable type 'Twilio.Exceptions.RestException' does not have a valid constructor. To correctly implement ISerializable a constructor that takes SerializationInfo and StreamingContext parameters should be present. Path '', line 1, position 110.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)\r\n   at Twilio.Exceptions.RestException.FromJson(String json)\r\n   at Twilio.Http.WebRequestClient.<MakeRequest>m__0(Exception x)\r\n   at System.AggregateException.Handle(Func`2 predicate)\r\n   at Twilio.Http.WebRequestClient.MakeRequest(Request request)\r\n   at Twilio.Clients.TwilioRestClient.Request(Request request)\r\n   at Twilio.Creators.Taskrouter.V1.WorkspaceCreator.Execute(ITwilioRestClient client)\r\n   at ..,
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nCreateISerializable\nNewtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed\nNewtonsoft.Json.Serialization.JsonSerializerInternalReader\nSystem.Object CreateISerializable(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonISerializableContract, Newtonsoft.Json.Serialization.JsonProperty, System.String)",
  "HResult": -2146233088,
  "Source": "Newtonsoft.Json",
  "WatsonBuckets": null

```

### Steps to Reproduce
1. Run the code.


### Feature Request
I'm probably doing something wrong, but I can't tell what... the exception isn't making it back to me.  
```

**Comment by compgumby** [comment]
More data...

This happens to me every time.  However, when I take the source and execute the "Execute" method by hand (providing the creator, the client, and the friendlyName), I can get the workspace to save.  However, if I try to do it again (intentionally attempting to create the same workspace twice), I get an exception:

ISerializable type 'Twilio.Exceptions.RestException' does not have a valid constructor

Here's the stack trace...

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Twilio.Exceptions.RestException.FromJson(String json)
   at Twilio.Http.WebRequestClient.<MakeRequest>m__0(Exception x)
   at System.AggregateException.Handle(Func`2 predicate)
   at Twilio.Http.WebRequestClient.MakeRequest(Request request)
   at Twilio.Clients.TwilioRestClient.Request(Request request)

**Comment by jingming** [comment]
This is resolved with the latest version of the library.
