### ISSUE TITLE
Iterating RecordingResource.Read() throws error

### ISSUE THREAD

**Issue by dprothero** [twilio/twilio-csharp#297]
**Version:** 5.0.0-rca2
**API Subdomain (api/taskrouter/ip_messaging):** Recordings

### Code Snippet
```c#
            TwilioClient.Init(Settings.TwilioAccountSid, Settings.TwilioAuthToken);
            var allRecordings = RecordingResource.Read();
            foreach (var r in allRecordings)
            {
                Console.WriteLine(r.Sid);
            }
```

### Exception / Log
```
System.Reflection.TargetInvocationException was unhandled
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Twilio.Base.ResourceSet`1.FetchNextPage()
       at Twilio.Base.ResourceSet`1.<GetEnumerator>c__Iterator0.MoveNext()
       at ConsoleApplication10.Program.Main(String[] args) in C:\Users\david\Documents\Visual Studio 2015\Projects\ConsoleApplication10\ConsoleApplication10\Program.cs:line 15
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233080
       Message=Index was outside the bounds of the array.
       Source=Twilio
       StackTrace:
            at Twilio.Converters.StringEnumConverter.MakeGenericType(Type objectType)
            at Twilio.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
            at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
            at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
            at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
            at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
            at Twilio.Base.Page`1.<FromJson>m__0(JToken record)
            at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
            at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
            at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
            at Twilio.Base.Page`1.FromJson(String recordKey, String json)
            at Twilio.Rest.Api.V2010.Account.RecordingResource.NextPage(Page`1 page, ITwilioRestClient client)
       InnerException: 
```

### Steps to Reproduce
1. Run the code above on account with recordings

**Comment by jingming** [comment]
Fixed.
