### ISSUE TITLE
Incorrect version of Newtonsoft.Json package

### ISSUE THREAD

**Issue by dprothero** [twilio/twilio-csharp#300]
**Version:**
5.0.0-rca2

### Code Snippet
```c#
TwilioClient.Init(
    Environment.GetEnvironmentVariable("TWILIO_ACCOUNT_SID"),
    Environment.GetEnvironmentVariable("TWILIO_AUTH_TOKEN")
);

var message = MessageResource.Create(
    from: new PhoneNumber("+15005551111"), 
    to: new PhoneNumber("+15005552222"),
    body: "What's up?",
    mediaUrl: new List<Uri>()
    {
        new Uri("https://c1.staticflickr.com/3/2899/14341091933_1e92e62d12_b.jpg")
    }
);

Debug.WriteLine(message.Sid);
```

### Exception / Log
```
System.IO.FileLoadException was unhandled
  FileName=Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///c:/users/david/documents/visual studio 2015/Projects/ConsoleApplication14/ConsoleApplication14/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Twilio, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: c:\users\david\documents\visual studio 2015\Projects\ConsoleApplication14\ConsoleApplication14\bin\Debug\ConsoleApplication14.vshost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///c:/users/david/documents/visual studio 2015/Projects/ConsoleApplication14/ConsoleApplication14/bin/Debug/Newtonsoft.Json.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

  HResult=-2146234304
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Twilio
  StackTrace:
       at Twilio.Rest.Api.V2010.Account.MessageResource.FromJson(String json)
       at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client)
       at Twilio.Rest.Api.V2010.Account.MessageResource.Create(PhoneNumber to, String accountSid, PhoneNumber from, String messagingServiceSid, String body, List`1 mediaUrl, Uri statusCallback, String applicationSid, Nullable`1 maxPrice, Nullable`1 provideFeedback, ITwilioRestClient client)
       at ConsoleApplication14.Program.Main(String[] args) in c:\users\david\documents\visual studio 2015\Projects\ConsoleApplication14\ConsoleApplication14\Program.cs:line 22
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

### Steps to Reproduce
1. In Visual Studio 2015, create a new Console application
2. From Package Manager Console, run `Install-Package Twilio -Pre`
3. Run the code above. It will send the text message, but crash with the error above.
4. Manually installing version v9.0.1 of the `Newtonsoft.Json` package from NuGet corrects the issue.

**Comment by hyankov** [comment]
This is not solved, why is it closed? I have just stumbled upon it with **Sendgrid** 9.1.0, **SendGrid.CSharp.HTTP.Client** 3.1.0 and **Newtonsoft.Json** 10.0.1

**Comment by hyankov** [comment]
I have just reproduced/stumbled upon this issue with version 5.1.0 and Newtonsoft.Json 10.0.1

> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by trifroggy** [comment]
Had the same issue but on 5.4.1 .  The SMS was sent as well, and the call back (for status) done, the exception happened afterwards.
Only remedy was similar as hyankov:  Downgrade to newtonsoft.json 9.0.1

**Comment by duncandavies** [comment]
I'm still having this issue occur even with a downgraded newtonsoft.json 9.0.1 installed
I am running 5.8.2 but have tried a few other versions (including 5.4.1 as trifroggy mentioned)

I can confirm using fiddler the request is sent and received correctly, it's just when trying to deserialize the response the issue is occurring within the Twilio Library

**Comment by Sufuninja** [comment]
Why is this issue closed? Having same issue but downgrading newtonsoft.json does not fix.
