### ISSUE TITLE
Serializing Twilio Api message object using Newtonsoft throws error

### ISSUE THREAD

**Issue by vinsaTimeparity** [twilio/twilio-csharp#335]
**Version 5.2**
 

### Code Snippet
```c#
# code 
try
            {
                // Find your Account Sid and Auth Token at twilio.com/console
                string accountSid = "accountid";
                string authToken = "token";
                TwilioClient.Init(accountSid, authToken);
                string _messsagingserviceid= "mid";
                var mediaUrl = new List<Uri>() {
            new Uri( "https://c1.staticflickr.com/3/2899/14341091933_1e92e62d12_b.jpg" )
        };
                var to = new Twilio.Types.PhoneNumber("+1234567890");
                MessageResource message = MessageResource.Create(
                    to,
                    messagingServiceSid: _messsagingserviceid,
                    body: "nw contents?");
                Console.WriteLine(JsonConvert.SerializeObject(message));
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.ToDetailedString());
            }
            
            Console.ReadKey();

``` 

### Exception / Log
```
System.ArgumentNullException: Value cannot be null.
Parameter name: o
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Twilio.Converters.PhoneNumberConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
```

### Steps to Reproduce
1. Send a sms ( using Messaging service) 
2. The sms is successfully sent.
3. Try to serialize the message object(returned by MessageResource.Create). A parsing error is thrown

**Comment by vijayanandkannan** [comment]
Twilio Version - Latest (5.x)

TwilioClient.Init(TextMessageServiceSetting.Current.TwiloSettingInfo.TwiloAccountSID, TextMessageServiceSetting.Current.TwiloSettingInfo.TwiloAuthtoken);

                    string phone = phoneNumber;

                    phone = "+" + phone;
                    var to = new PhoneNumber(phone);
                    try
                    {
                        var message = MessageResource.Create(
                            to, from: new PhoneNumber(TextMessageServiceSetting.Current.TwiloSettingInfo.TwiloVirtualNumber), body: smsMessage);
                        resultValue = 200;
                    }
                    catch (Exception ex)
                    {
                        Logger.LogError("Twilio Error : " + ex.Message, "Text Message - Twilio", ex);
                        resultValue = 200;
                    }


I am receiving the message, but it throws up the Newtonsoft.Json Error

#########################

Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"
##############################


I have signed the Twilio with Strong name.

Also can you provide Twilio with strong name with each release, otherwise we need download and sign with strong name.

![image](https://cloud.githubusercontent.com/assets/14199725/24758842/31767d6a-1aa9-11e7-9e30-9d7ff551ee4d.png)

Thanks

Vijay

**Comment by dprothero** [comment]
@jingming @efossier it would be great to be able to serialize a resource class. Not sure why it isn't working.

**Comment by lpghartz** [comment]
Any update/progress on this? I ran into this, as well, when upgrading our code from the 4.x to 5.x libraries -- for diagnostic purposes we log responses, and everywhere that does that is blowing up.

**Comment by efossier** [comment]
@vinsaTimeparity @dprothero @lpghartz I've created a ticket to track this work and will be taking a look today.

**Comment by efossier** [comment]
@vinsaTimeparity @lpghartz I was able to run the code provided above without problem and the message was correctly serialized to json. Can you elaborate on which versions of .Net and 
 Newtonsoft you are using?

**Comment by vinsaTimeparity** [comment]
@efossier in my case it was  .net 4.5.2 , NewtonSoft.Json 9.0.1

**Comment by efossier** [comment]
@vinsaTimeparity I believe I was running it on .Net 4.6 and NewtonSoft.Json 9.0.1 so pretty close to your setup. What do you get when you print `message.ToString()`? Does everything look correct?

Im happy to keep trying things out to help you debug but I cannot reproduce and im not very familiar to C# so not sure what else to try.

**Comment by tfierens** [comment]
I just found thread just after having reported it to Twilio directly. 

I've just included Twilio as a new component in our app but I upgraded from 9.0.1 to 10.0.3 as I'm using the latter in various existing components in our app.

Text did send earlier on even after an error occurred but now I've just tried it with a Colleague's mobile and text are no longer being sent but I'm still getting the same error. 

I've include the following in my app.config as I had the same problem with the Dropbox API:

`      
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
            <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>      
`
It resolved the problem for Dropbox but not for Twilio. 

Any suggestions?

Thanks.

**Comment by efossier** [comment]
@tfierens @vinsaTimeparity I upgraded Newtonsoft to 10.0.0.3 on my test machine and it is still serializing as expected... I'm starting to think since the stacktrace shows the error occurs in `PhoneNumberConverter` that perhaps it works with my messages because i have standard US phone numbers in my message json, perhaps this is an issue with a different type of number. Which country phone numbers are you using to and from? (Country is enough).

**Comment by tfierens** [comment]
@efossier. I noticed the same. I went to check my original test app which was a basic console app and it is using Twilio 5.5.2 and Newtonsoft 10.0.3 which means it's definitely working with it but I think you're on to something regarding the numbers. Not so much the formatting but maybe the numbers that are allowed or not as I'm using the eval. I'm wondering if I'm only allowed to send text to numbers that have been confirmed if it is it an unconfirmed number, does it try to serialize an error and throwing this error. I'll confirm in a bit.

**Comment by tfierens** [comment]
@efossier - Nope that's not it! I've just tried it with a registered number and I'm getting the same error. I can't actually spot what's different between my console app and this specific component. I'll keep looking into it. My sender number is a US mobile and my receiver  mobile is an Irish number (+353999999999).

**Comment by efossier** [comment]
@tfierens I dont think it has to do with your number not being allowed or not, those checks happen at the api layer and the api would return some form of 4xx in that case which would throw an ApiException. I think more likely is that our Phone number serialization doesnt support some specific phone number formats that we are receiving. 

One interesting thing we could do is for you to try the request that is causing this serialization error in curl or the api explorer, and see what the api responds. Then we can see if theres anything obvious that would cause a problem in serializing it into C# objects.

**Comment by jmctwilio** [comment]
Closing this due to inactivity and inability to reproduce.  If it remains an issue with the latest library versions, please submit a new issue.
