### ISSUE TITLE
Error parsing Infinity value. Path '', line 1, position 1.

### ISSUE THREAD

**Issue by Ramin-Bateni** [twilio/twilio-csharp#386]
Hi, I have ASP.NET MVC project and call the bellow method in its codes but it return an exception with this message:
 `"Error parsing Infinity value. Path '', line 1, position 1."` 
It dose not send the SMS.
It seems the error is about Json Deserializing.

I checked _AccountSid_, _AuthToken_, _DestinationPhoneNo_, _Twilio_PhoneNo_ and _Body_. All the values are correct!

What is the reason of this problem?

**Version:**
5.6.0.0

### Code
```
private MessageResource SendSmsByTwilio(IdentityMessage message)
{
        Twilio.TwilioClient.Init(Consts.Twilio_AccountSid, Consts.Twilio_AuthToken);

        return MessageResource.Create(
                to: new PhoneNumber(message.Destination),
                from: new PhoneNumber(Consts.Twilio_PhoneNo),
                body: message.Body);
}
```
### StackTrace
```
   at Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(ReadType readType, Boolean matched)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Twilio.Clients.TwilioRestClient.ProcessResponse(Response response)
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(PhoneNumber to, String pathAccountSid, PhoneNumber from, String messagingServiceSid, String body, List`1 mediaUrl, Uri statusCallback, String applicationSid, Nullable`1 maxPrice, Nullable`1 provideFeedback, Nullable`1 validityPeriod, String maxRate, Nullable`1 forceDelivery, String providerSid, ContentRetentionEnum contentRetention, AddressRetentionEnum addressRetention, ITwilioRestClient client)
   .
   .
   .
```
![image](https://user-images.githubusercontent.com/9051320/28800306-525210f8-7661-11e7-8bc9-661e179eb4cf.png)

**Comment by jmctwilio** [comment]
We are unable to reproduce the issue in a console application.  Unfortunately, we've removed support for MVC in our helper libraries.  If you continue to experience this issue, please submit an issue and provide more information about your environment.
