### ISSUE TITLE
Connection Forcibly Closed Sending SMS

### ISSUE THREAD

**Issue by DazFahy** [twilio/twilio-csharp#415]
Hi
   We are randomly getting a "System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host". It only appears to happen maybe once every 3 or 4 days.

The way our code works is that we are checking to see if in our database there are any new messages which need to be sent. If there are we call TwilioClient.Init then loop round the messages and send them with MessageResource.Create

We check for new message every 10 seconds and then if we need to send repeat the above process.

# Stack Trace

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twilio.Http.SystemNetHttpClient.<MakeRequestAysnc>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Twilio.Http.SystemNetHttpClient.MakeRequest(Request request)
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(CreateMessageOptions options, ITwilioRestClient client)
   at Twilio.Rest.Api.V2010.Account.MessageResource.Create(PhoneNumber to, String pathAccountSid, PhoneNumber from, String messagingServiceSid, String body, List`1 mediaUrl, Uri statusCallback, String applicationSid, Nullable`1 maxPrice, Nullable`1 provideFeedback, Nullable`1 validityPeriod, ITwilioRestClient client)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Twilio.Http.SystemNetHttpClient.<MakeRequestAysnc>d__4.MoveNext()<---

**Comment by alexey-grebennikov** [comment]
Hello, we have almost the same case. 

Do you have any expected time frame when the issue will be investigated and fixed?

**Comment by dsghi** [comment]
You're posting on someone's issue that is over a year old... If you can give some more specific details on your situation and provide some code samples to reproduce, the community here will try to help you. If want a reply directly from Twilio you'll need to open a support request at https://support.twilio.com

**Comment by alexey-grebennikov** [comment]
Thanks @dsghi for your comment.

Here are more details:

Here is the code how my service is registered in ioc container: builder.RegisterType<MessageSender>().As<IMessageSender>();

I init twilio in my service constructor: TwilioClient.Init(_config.AccountSid, _config.AuthToken); 

Here is the code that sends SMS:
public async Task SendSmsAsync(string toPhoneNumber, string body)
{
	var to = new PhoneNumber(AddCountryUSACode(toPhoneNumber));
	var resource = await MessageResource.CreateAsync(to,
                    from: new PhoneNumber(_config.FromPhoneNumber), body: body);
}

I send SMS every 5-10 minutes and every 4-5 days I have the following error:
Twilio.Exceptions.ApiConnectionException: Connection Error: POSThttps://api.twilio.com/2010-04-01/Accounts/*********/Messages.json ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.

**Comment by thinkingserious** [comment]
Thanks for helping out @dsghi!

Hello @DazFahy, @alexey-grebennikov,

This looks to be a connection issue between our server and yours. My first recommendation is to be sure your code implements a retry when this issue occurs. Secondly, I would suggest you reach out to our [support team](https://support.twilio.com) directly as I do not think this is a library issue.

With best regards,

Elmer
