### ISSUE TITLE
Specifying the Region in TwilioRestClient results in a 502

### ISSUE THREAD

**Issue by shaunbowe** [twilio/twilio-csharp#419]
Version: 5.10.0

### Code Snippet
```csharp
# var client = new TwilioRestClient("username", "password", region:"au1");
```

### Exception/Log
```
Twilio.Exceptions.ApiConnectionException: Connection Error: POST https://api.au1.twilio.com/2010-04-01/Accounts/AC0b022a7ef4b343bcaf228d979a0207af/Calls.json ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'api.au1.twilio.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Twilio.Http.SystemNetHttpClient.MakeRequest(Request request)
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   --- End of inner exception stack trace ---
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Montage.Internal.Voice.API.Web.Areas.Interview.Core.TwilioMontageInterviewService.TryCall(TwilioRestClient client, CreateCallOptions callOptions, String culture) in E:\Agent2\_work\91\s\Montage.Internal.Voice.API.Web\Areas\Interview\Core\TwilioMontageInterviewService.cs:line 44
```

### Steps to Reproduce
1. Specify the region in the TwilioRestClient constructor
2. Attempt to use the rest client
3. blow up

**Comment by adamchester** [comment]
Same problem here. Any news on this?

**Comment by imthepitts** [comment]
Hello, 

Sorry for the radio silence on this issue. Twilio's REST API does not currently support other regions (e.g. api.au1.twilio.com). The `region` parameter is used for internal purposes. Apologies for the confusion.

Zack
