### ISSUE TITLE
Serializing MessageResource response object using Newtonsoft throws error

### ISSUE THREAD

**Issue by johnbaker** [twilio/twilio-csharp#423]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**
5.12.1

### Code Snippet
```csharp
	 try
            {
                // Find your Account Sid and Auth Token at twilio.com/console
				string accountSid = "sid";
				string authToken = "token";
                TwilioClient.Init(accountSid, authToken);
				string _messsagingserviceid = "serviceid";
                var to = new Twilio.Types.PhoneNumber("+15555555555");
                MessageResource message = MessageResource.Create(
                    to,
                    messagingServiceSid: _messsagingserviceid,
                    body: "nw contents?");
                Console.WriteLine(JsonConvert.SerializeObject(message));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

```

### Exception/Log
```
System.ArgumentNullException: Value cannot be null.
Parameter name: o
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Twilio.Converters.PhoneNumberConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at SerializeMessageResourceFails.Program.Main(String[] args) in /Users/jbaker/Projects/SerializeMessageResourceFails/SerializeMessageResourceFails/Program.cs:line 24
```

### Steps to Reproduce
1.  Use MessageResource.create sending using a messageServiceId (leaving "from" null) to send a message
2. The sms is successfully sent
3. Attempt to serialize the response using JsonConvert.SerializeObject 
4. See exception.

If I provide a "from", the result will successfully serialize.  If I use reflection to set the "From" property to a non-null value it serializes:
```csharp
message.GetType().GetProperty("From").SetValue(message, new Twilio.Types.PhoneNumber(""));
```

This was previously reported and closed as not reproducible in  #335

Attached is a sample .NET core command line console app demonstrating the issue.   sids and tokens replaced with placeholders.
[Archive.zip](https://github.com/twilio/twilio-csharp/files/1992287/Archive.zip)

**Comment by thinkingserious** [comment]
Hello @johnbaker,

Are you still experiencing this issue utilizing the latest version of this library? I believe [this PR](https://github.com/twilio/twilio-csharp/pull/447) may have solved the issue. If not, please let us know.

With best regards,

Elmer

**Comment by hoppities** [comment]
I'm seeing the exact same issue mentioned here.

**Comment by childish-sambino** [comment]
@hoppities Are you using the latest version of the library? Could you also post sample code that shows the error?

**Comment by CodeFisher-02** [comment]
I am using Newtonsoft.Json ver 12.0.3 with .net Core 3.1. 

I am unable to serialize messageResource when instead of from , messagingServiceSid is used as a parameter 

 message = await MessageResource.CreateAsync
            (
                body: body,
                messagingServiceSid: serviceId,
                to: new PhoneNumber(phoneNumber)
            );

It throws a null exception, possibly because I am not passing from as a parameter
