### ISSUE TITLE
CallResource.update not working to modify ongoing calls

### ISSUE THREAD

**Issue by SafeCab** [twilio/twilio-csharp#508]
I am using the Twilio REST API helper library version 5.35.1.0 for c#

hi,

I am trying to use the following code to talk over a call

  var call = CallResource.Update(
                twiml: "<Response><Say>Ahoy there me hearties</Say></Response>",
                pathSid: CallId
            );

The call Id was CA21ff8ca37fda618608ba7847540a6ad4

The error is

tTwilio.Clients.TwilioRestClient.ProcessResponse(Response response)
   at Twilio.Clients.TwilioRestClient.Request(Request request)
   at Twilio.Rest.Api.V2010.Account.CallResource.Update(UpdateCallOptions options, ITwilioRestClient client)
   at Twilio.Rest.Api.V2010.Account.CallResource.Update(String pathSid, String pathAccountSid, Uri url, HttpMethod method, UpdateStatusEnum status, Uri fallbackUrl, HttpMethod fallbackMethod, Uri statusCallback, HttpMethod statusCallbackMethod, String twiml, ITwilioRestClient client)

InnerException='Upgrade Required"

I am using the latest version though 

Thanks

Steve

**Comment by childish-sambino** [comment]
Check this out: https://www.twilio.com/docs/api/errors/20426
