### ISSUE TITLE
The response ended prematurely. Call to SMS service

### ISSUE THREAD

**Issue by MrZoidberg** [twilio/twilio-csharp#572]
### Issue Summary
We are using twilio-csharp lib in the .NET Core 3.1 web service running in EKS. In the REST API call we have the code that sends SMS code.

We don't see any pattern in this exception like input data or anything else.

### Code Snippet
```csharp
TwilioClient.Init(this._twilioOptions.AccountSid, this._twilioOptions.AuthToken);

try
{
    var response = await MessageResource.CreateAsync(
        body: smsRequest.Message,
        from: new Twilio.Types.PhoneNumber(this._twilioOptions.Number),
        to: new Twilio.Types.PhoneNumber(smsRequest.To));

    return true;
}
catch (Twilio.Exceptions.ApiException e)
{
    this._logger.LogError($"Failed to send sms via Twillio. Error code: {e.Code}");
    return false;
}
```

### Exception/Log
```
message_@x
    Twilio.Exceptions.ApiConnectionException: Connection Error: POSThttps://api.twilio.com/2010-04-01/Accounts/[AccountNumber]/Messages.json
     ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
     ---> System.IO.IOException: The response ended prematurely.
       at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
       at Twilio.Http.SystemNetHttpClient.MakeRequestAsync(Request request)
       at Twilio.Clients.TwilioRestClient.RequestAsync(Request request)
       --- End of inner exception stack trace ---
       at Twilio.Clients.TwilioRestClient.RequestAsync(Request request)
       at Twilio.Rest.Api.V2010.Account.MessageResource.CreateAsync(CreateMessageOptions options, ITwilioRestClient client)
       at Twilio.Rest.Api.V2010.Account.MessageResource.CreateAsync(PhoneNumber to, String pathAccountSid, PhoneNumber from, String messagingServiceSid, String body, List`1 mediaUrl, Uri statusCallback, String applicationSid, Nullable`1 maxPrice, Nullable`1 provideFeedback, Nullable`1 validityPeriod, Nullable`1 forceDelivery, ContentRetentionEnum contentRetention, AddressRetentionEnum addressRetention, Nullable`1 smartEncoded, List`1 persistentAction, ITwilioRestClient client)
       at SendSmsAsync(SmsRequest smsRequest) in /src/SmsSender.cs:line 52
       at CreateVerificationCommand.ExecuteAsync() in /src/CreateVerificationCommand.cs:line 75
       at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
       at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```

### Technical details:
* twilio-csharp version:  5.39.0
* csharp version: netstandard2.1

**Comment by thinkingserious** [comment]
Hello @MrZoidberg,

Is this an intermittent issue or do you always see this error? I'd like to get an understanding around the frequency of the issue. Thanks!

With best regards,

Elmer

**Comment by MrZoidberg** [comment]
Hello @thinkingserious. We had around 6-8 errors for the whole of June 2021. I can't say we are actively using CurrencyCloud API, but I think that there are similar API requests from our backend almost every day.

**Comment by thinkingserious** [comment]
Hello @MrZoidberg,

I'm not sure the relation of CurrencyCould API in this context, could you please elaborate?

Are the 6-8 errors a significant amount in relation to your total number of calls for June? If not, I suggest implementing a [retry strategy](https://www.twilio.com/docs/usage/rest-api-best-practices#retry-with-exponential-backoff). You may also want to increase the timeout value ([example](https://github.com/twilio/twilio-csharp/issues/500#issuecomment-557710213)).

With best regards,

Elmer

**Comment by MrZoidberg** [comment]
Sorry, just a typo. I meant Twillio. I would say that's around 0.01% of our total monthly requests. So your recommendation is to do retries in this case?

**Comment by thinkingserious** [comment]
Thanks for the clarification @MrZoidberg. I would increase the timeout and implement a retry strategy.

**Comment by luismejia-iq** [comment]
@MrZoidberg my team is facing the same issue with a few requests, small percentage I would say.  I wonder if you were able to find out the root cause? did a longer time out helped ?  we currently use a 5 second timeout. 

Documentation on the error suggest that the server itself (Twilio in this case) is the one closing the connection before getting a full response
